#!/bin/sh
echo "=== Extracting wiringPi ===\n"
tar xzvf wiringPi.tgz >/dev/null
echo "\n=== Building and installing wiringPi ===\n"
cd wiringPi
./build
cd ..
echo "\n=== Building and installing kaku ===\n"
g++ -o kaku kaku.cpp -I/usr/local/include  -L/usr/local/lib -lwiringPi
sudo cp kaku /usr/bin
sudo chmod +s /usr/bin/kaku
echo "\n=== Finished, kaku installed in /usr/bin, type kaku add prompt to use it ==="